### ISSUE TITLE
Few minor issues with the user API

### ISSUE THREAD

**Issue by ThrownLemon** [ConcealNetwork/conceal-cloud#14] opened 2020-08-11 11:55 UTC
Request URL: https://api.wallet.conceal.network/api/user
{"result":"success","message":[true]}

Found a few issues with the Signup/Signin API.

1. When creating a new account i'm able to keep signing up with the same details without getting any error response.

2. There is no message given to the user that they must activate their account after signing up.

3. If you don't activate your account via email you get the following message when trying to sign in:  
**"User/password don't match. Please try again."** It would be better say **"Your account is pending activation, please check your email"**

4. The email sent to activate your account comes from <zemanel@conceal.network> which okay but should be generic such as cloud@conceal.network or admin@conceal.network

5. When you click the activate link, it doesn't tell you the account was activated and your also not taken to the login form... just the main page.

**Comment by krypt0x** [comment] 2020-08-11 12:59
The team will have a look at it ASAP. Thank you.

**Comment by bomb-on** [comment] 2020-08-16 10:55
Summary from Discord conversation and some updates related to this:

1. This is by design
2. Will be fixed in next release
3. This is by design, related to the first issue
4. This will be fixed sometimes soon (@cryptomanel)
5. @cryptomanel can you confirm that after account is activated, user is redirected to `/login?activated`?

**Comment by krypt0x** [comment] 2021-01-17 00:27
This has definitely been fixed.

**Closed by krypt0x** 2021-01-17 00:27 UTC
Labels: enhancement
